gql start
mrfourfour/graph_server pull request #1
Opened 2019-09-24 17:31 UTC by WonBeomChoi

2019-09-25 00:58 UTC, aerain requested changes
이부분만 수정해서 다시 고고싕

2019-09-25 00:58 UTC, aerain commented on app.js
> +        const res = await (await fetch('http://ticket.ap-northeast-2.elasticbeanstalk.com/api/ticket')).json();
```js
const res =  await (await(fetch()).json();
...
return res.data;
```

이부분을

```js
const { data } = await (await fetch()).json();
...
return data;
```

이렇게 바꿀수도 있어용

2019-09-25 00:58 UTC, aerain commented on app.js
> +        let res = await (await fetch('http://ticket.ap-northeast-2.elasticbeanstalk.com/api/ticket/'+id)).json();
마찬가지

2019-09-25 00:58 UTC, aerain commented on app.js
> +        console.log(qrData);
올릴때는 디버깅했던 내용 삭제 필수쓰

2019-09-29 12:00 UTC, WonBeomChoi commented on app.js
> +        const res = await (await fetch('http://ticket.ap-northeast-2.elasticbeanstalk.com/api/ticket')).json();
반영 완료

2019-09-29 12:00 UTC, WonBeomChoi commented on app.js
> +        console.log(qrData);
해결

2019-09-29 12:00 UTC, WonBeomChoi commented on app.js
> +        let res = await (await fetch('http://ticket.ap-northeast-2.elasticbeanstalk.com/api/ticket/'+id)).json();
마찬가지 해결

2019-09-29 12:02 UTC, aerain commented
굳

2019-09-29 12:02 UTC, merged